name: Daily Job Hunter

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  hunt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          pip install -r src/requirements.txt

      - name: Test Google Sheet
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: |
          python src/test_sheet.py

      - name: Test Remote Jobs API
        run: |
          python src/fetch_remote_jobs.py
      
   #   - name: Fetch Jobs
   #      env:
   #        APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
   #      run: |
   #        python src/fetch_jobs.py

   #    - name: Send Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python src/telegram_notify.py
